apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  instances: 1

  imageName: deathsamsul/postgres-cnpg:17.5-pgvector
  imagePullPolicy: IfNotPresent

  enableSuperuserAccess: true

  superuserSecret:
    name: postgres-admin-secret

  storage:
    size: 10Gi
    storageClass: hostpath

  bootstrap:
    initdb:
      database: postgres
      owner: postgres_admin