apiVersion: batch/v1
kind: Job
metadata:
  name: initial-model
  namespace: fraud-mlops
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: initial-model
          image: fraud-mlops-jobs:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "app.startup_jobs.initial_model"]
          envFrom:
            - configMapRef:
                name: fraud-mlops-config
            - secretRef:
                name: fraud-db-secret
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp_data
      volumes:
        - name: temp-data
          emptyDir: {}