apiVersion: batch/v1
kind: Job
metadata:
  name: initial-model  
  namespace: fraud-mlops
spec:
  ttlSecondsAfterFinished: 360  # Automatically clean up the Job after 6m of completion (success or failure)
  backoffLimit: 1        # Controls how many times Kubernetes retries the Job if it fails. After that → marked as failed permanently

  template:
    spec:
      restartPolicy: Never  # If the container stops (success or failure) Kubernetes will NOT restart it inside the same Pod
      containers:
        - name: initial-model
          image: deathsamsul/startup_job:1.1
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "app.startup_jobs.initial_model"]
          envFrom:
            - configMapRef:
                name: fraud-mlops-config
            - secretRef:
                name: fraud-db-secret
          volumeMounts:
            - name: temp-data
              mountPath: /tmp/temp_data
      volumes:
        - name: temp-data
          emptyDir: {}