apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-dataset-pvc
  namespace: fraud-mlops
spec:
  storageClassName: standard  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi