apiVersion: v1
kind: Secret
metadata:
  name: fraud-db-secret
  namespace: fraud-mlops
type: Opaque
stringData:
  TRAINING_DATA_STORE_URL: "postgresql+psycopg2://training_user:train123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
