apiVersion: batch/v1
kind: Job
metadata:
  name: store-training-data
  namespace: fraud-mlops
spec:
  backoffLimit: 1     # Retry the Job only once if it fails
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: store-training-data
          image: deathsamsul/startup_job:1.1
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "app.startup_jobs.store_train_data"]
          envFrom:
            - configMapRef:
                name: fraud-mlops-config
            - secretRef:
                name: fraud-db-secret
          volumeMounts:
            - name: dataset
              mountPath: /opt/datasets
              readOnly: true
            - name: temp-data
              mountPath: /tmp/temp_data
      volumes:
        - name: dataset
          persistentVolumeClaim:
            claimName: fraud-dataset-pvc
        - name: temp-data
          emptyDir: {}