apiVersion: v1
kind: Pod
metadata:
  name: dataset-copy-pod
  namespace: fraud-mlops
spec:
  restartPolicy: Never  # The Pod will not restart if the container stops (success or failure)
  containers:
    - name: copy
      image: busybox:1.36   # A lightweight image with basic Unix utilities
      command: ["sleep", "3600"]  # stays alive for 3600 seconds (1 hour) to allow us to exec into it and copy data
      volumeMounts:
        - name: dataset
          mountPath: /opt/datasets
  volumes:
    - name: dataset
      persistentVolumeClaim:
        claimName: fraud-dataset-pvc