apiVersion: v1
kind: Secret
metadata:
  name: fraud-api-secret
  namespace: fraud-api
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  PREDICTION_DATABASE_URL: "postgresql+psycopg2://prediction_user:predict123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
  METRICS_DB_URL: "postgresql+psycopg2://metrics:metrics123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
  TRAINING_DATA_STORE_URL: "postgresql+psycopg2://training_user:train123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
  DATABASE_URL: "postgresql+psycopg2://mlflow:mlflow1@postgres-cluster-rw.database.svc.cluster.local:5432/mlflowdb"