apiVersion: v1
kind: Secret

metadata:
  name: postgres-admin-secret    # must match the name used in statefulset.yaml
  namespace: database        # namespace must match the one defined in namespace.yaml
type: kubernetes.io/basic-auth   # this type is suitable for storing username and password
stringData:               

  username: postgres_admin
  password: admin_password
