apiVersion: v1
kind: Service
metadata:
  name: postgres-service # name of the service
  namespace: database   # namespace must match the one defined in namespace.yaml
spec:
  selector:
    app: postgres # this label must match the label in statefulset.yaml on template.metadata.labels
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP