apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  BACKEND_STORE_URI: postgresql://mlflow:mlflowpassword@postgres:5432/mlflow
  ARTIFACT_ROOT: s3://mlflow/
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000

