apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: deathsamsul/mlflow:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          env:
            - name: BACKEND_STORE_URI
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: BACKEND_STORE_URI

            - name: ARTIFACT_ROOT
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: ARTIFACT_ROOT

            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: MINIO_ACCESS_KEY

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: MINIO_SECRET_KEY