apiVersion: v1
kind: Secret
metadata:
  name: monitoring-dashboard-secret
  namespace: ml-monitoring
type: Opaque
stringData:
  PREDICTION_DATABASE_URL: "postgresql+psycopg2://prediction_user:predict123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
  TRAINING_DATA_STORE_URL: "postgresql+psycopg2://training_user:train123@postgres-cluster-rw.database.svc.cluster.local:5432/appdata"
  