apiVersion: v1
kind: Service
metadata:
  name: monitoring-dashboard-service
  namespace: ml-monitoring
spec:
  type: NodePort
  selector:
    app: monitoring-dashboard
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501